from shogi import *

MOVE_DIRECTION = [
    UP, UP_LEFT, UP_RIGHT,
    DOWN, DOWN_LEFT, DOWN_RIGHT,
    LEFT, RIGHT, UP2_LEFT, UP2_RIGHT,

    # 駒を成らせる
    UP_PROMOTE, UP_LEFT_PROMOTE, UP_RIGHT_PROMOTE,
    DOWN_PROMOTE, DOWN_LEFT_PROMOTE, DOWN_RIGHT_PROMOTE,
    LEFT_PROMOTE, RIGHT_PROMOTE, UP2_LEFT_PROMOTE, UP2_RIGHT_PROMOTE
]

MOVE_DIRECTION_PROMOTED = [
    UP_PROMOTE, UP_LEFT_PROMOTE, UP_RIGHT_PROMOTE,
    DOWN_PROMOTE, DOWN_LEFT_PROMOTE, DOWN_RIGHT_PROMOTE,
    LEFT_PROMOTE, RIGHT_PROMOTE, UP2_LEFT_PROMOTE, UP2_RIGHT_PROMOTE
]

MOVE_DIRECTION_LABEL_NUM = len(MOVE_DIRECTION) + 7  # 7は持ち駒の種類数
